# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0026_auto_20160407_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'consumo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'fecha')),
                ('canceled', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Order')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'consumo')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='venta.Product')),
                ('code', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to=b'plates/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'fecha')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
            },
            bases=('venta.product',),
        ),
        migrations.CreateModel(
            name='SetTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'fecha')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venta.Order')),
            ],
            options={
                'verbose_name': 'Asignacion de Mesa',
                'verbose_name_plural': 'Asignaciones de Mesa',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('stock', models.FloatField(blank=True, null=True)),
                ('minimun_stock', models.FloatField(blank=True, null=True, verbose_name=b'stock m\xc3\xadnimo')),
                ('stock_refill', models.FloatField(blank=True, null=True, verbose_name=b'stock de relleno')),
                ('unidad', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Suministro',
                'verbose_name_plural': 'Suministros',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.AddField(
            model_name='settable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Table'),
        ),
        migrations.AddField(
            model_name='consumptiondish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Dish'),
        ),
        migrations.AddField(
            model_name='consumptiondish',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Supply', verbose_name=b'suministro'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Product', verbose_name=b'producto'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Supply', verbose_name=b'suministro'),
        ),
    ]
