# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name=b'Cancelado'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Order', verbose_name=b'Orden'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='code',
            field=models.CharField(max_length=45, verbose_name=b'C\xc3\xb3digo'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to=b'plates/', verbose_name=b'Foto'),
        ),
        migrations.AlterField(
            model_name='settable',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venta.Order', verbose_name=b'Orden'),
        ),
        migrations.AlterField(
            model_name='settable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Table', verbose_name=b'Mesa'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=45, verbose_name=b'Nombre'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=45, verbose_name=b'Nombre'),
        ),
        migrations.AlterField(
            model_name='table',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name=b'Servicio'),
        ),
    ]
