# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0002_auto_20160407_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name=b'Codigo')),
                ('buy_count', models.IntegerField(verbose_name=b'Cantidad')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Supply', verbose_name=b'Suministro')),
            ],
            options={
                'verbose_name': 'Compra de Suministro',
                'verbose_name_plural': 'Compra de Suministros',
            },
        ),
        migrations.AlterField(
            model_name='consumption',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.BuySupply', verbose_name=b'suministro'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha'),
        ),
    ]
