# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0003_auto_20160408_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='buysupply',
            name='current_count',
            field=models.IntegerField(default=0, verbose_name=b'Cantidad Actual'),
            preserve_default=False,
        ),
    ]
