# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0004_buysupply_current_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='method',
            field=models.BooleanField(choices=[(b'PEPS', True), (b'UEPS', False)], default=True, verbose_name=b'M\xc3\xa9todo'),
            preserve_default=False,
        ),
    ]
