# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0005_supply_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buysupply',
            name='current_count',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Cantidad Actual'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='method',
            field=models.BooleanField(choices=[(True, b'PEPS'), (False, b'UEPS')], default=True, verbose_name=b'M\xc3\xa9todo'),
        ),
    ]
