# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0006_auto_20160411_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='buysupply',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 19, 15, 13, 86581, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
