# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0007_buysupply_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Cantidad')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.Supply', verbose_name=b'suministro')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Items del pedido',
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido de Suministro',
                'verbose_name_plural': 'Pedidos de Suministros',
            },
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='supplyrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorant.SupplyRequest', verbose_name=b'Petici\xc3\xb3n de suministro'),
        ),
    ]
