# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0008_auto_20160412_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='aviable',
            field=models.BooleanField(default=True),
        ),
    ]
