# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0009_table_aviable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBuySupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=45, verbose_name=b'Codigo')),
            ],
        ),
        migrations.RemoveField(
            model_name='buysupply',
            name='code',
        ),
    ]
