# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0010_auto_20161119_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billbuysupply',
            options={'verbose_name': 'Factura de Compra', 'verbose_name_plural': 'Facturas de Compras'},
        ),
        migrations.AddField(
            model_name='buysupply',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restorant.BillBuySupply', verbose_name=b'codigo Factura'),
            preserve_default=False,
        ),
    ]
