# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0059_config_name'),
        ('restorant', '0012_supply_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name=b'Servicio'),
            preserve_default=False,
        ),
    ]
