# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-09 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0062_auto_20161202_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.IntegerField(choices=[(1, b'Descuento'), (2, b'unidades')])),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('oferta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Oferta')),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
            },
            bases=('promocion.oferta',),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('oferta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Oferta')),
                ('nombre', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Promoci\xf3n',
                'verbose_name_plural': 'Promociones',
            },
            bases=('promocion.oferta',),
        ),
        migrations.AddField(
            model_name='oferta',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service'),
        ),
        migrations.CreateModel(
            name='BCategoria',
            fields=[
                ('promocion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Promocion')),
            ],
            options={
                'verbose_name': 'Bono Categoria',
                'verbose_name_plural': 'Bonos Categorias',
            },
            bases=('promocion.promocion',),
        ),
        migrations.CreateModel(
            name='BMarca',
            fields=[
                ('promocion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Promocion')),
            ],
            options={
                'verbose_name': 'Bono Marca',
                'verbose_name_plural': 'Bonos de Marcas',
            },
            bases=('promocion.promocion',),
        ),
        migrations.CreateModel(
            name='BProducto',
            fields=[
                ('promocion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Promocion')),
            ],
            options={
                'verbose_name': 'Bono de Producto',
                'verbose_name_plural': 'Bonos de Productos',
            },
            bases=('promocion.promocion',),
        ),
        migrations.CreateModel(
            name='PCategoria',
            fields=[
                ('promocion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Promocion')),
            ],
            options={
                'verbose_name': 'Promoci\xf3n de Categor\xeda',
                'verbose_name_plural': 'Promocines de Categorias',
            },
            bases=('promocion.promocion',),
        ),
        migrations.CreateModel(
            name='PMarca',
            fields=[
                ('promocion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Promocion')),
            ],
            options={
                'verbose_name': 'Promoci\xf3n de Marca',
                'verbose_name_plural': 'Promociones de Marcas',
            },
            bases=('promocion.promocion',),
        ),
        migrations.CreateModel(
            name='PProducto',
            fields=[
                ('promocion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promocion.Promocion')),
                ('producto', models.ManyToManyField(to='venta.Product')),
            ],
            options={
                'verbose_name': 'Promoci\xf3n de Producto',
                'verbose_name_plural': 'Promociones de productos',
            },
            bases=('promocion.promocion',),
        ),
    ]
