# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-09 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0063_auto_20170109_1526'),
        ('promocion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmarca',
            name='marcas',
            field=models.ManyToManyField(to='venta.Brand'),
        ),
        migrations.AddField(
            model_name='pcategoria',
            name='categorias',
            field=models.ManyToManyField(to='venta.Category'),
        ),
        migrations.AddField(
            model_name='bproducto',
            name='producto',
            field=models.ManyToManyField(to='venta.Product'),
        ),
        migrations.AddField(
            model_name='bmarca',
            name='marcas',
            field=models.ManyToManyField(to='venta.Brand'),
        ),
        migrations.AddField(
            model_name='bcategoria',
            name='categorias',
            field=models.ManyToManyField(to='venta.Category'),
        ),
    ]
