# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0002_auto_20170109_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo',
            field=models.IntegerField(choices=[(1, b'Descuento'), (2, b'Monto')]),
        ),
    ]
