# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propduct',
            new_name='Product',
        ),
    ]
