# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20160125_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.Service'),
            preserve_default=False,
        ),
    ]
