# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_userservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Service'),
        ),
    ]
