# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_client_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.Service'),
            preserve_default=False,
        ),
    ]
