# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20160205_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('url', models.ImageField(upload_to='category_images/')),
            ],
        ),
    ]
