# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_auto_20160206_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='precentation',
            new_name='presentation',
        ),
    ]
