# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_auto_20160206_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='payment_method',
            new_name='cash',
        ),
        migrations.AddField(
            model_name='bill',
            name='card',
            field=models.CharField(default='0', max_length=45),
        ),
        migrations.AddField(
            model_name='bill',
            name='check',
            field=models.CharField(default='0', max_length=45),
        ),
        migrations.AddField(
            model_name='bill',
            name='disscount',
            field=models.CharField(default='0', max_length=45),
        ),
    ]
