# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_auto_20160207_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
