# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_auto_20160207_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipconsumo', models.IntegerField(default=0)),
                ('propina', models.IntegerField(default=0)),
            ],
        ),
    ]
