# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='ipconsumo',
            new_name='ipoconsumo',
        ),
    ]
