# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0019_auto_20160207_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=True),
        ),
    ]
