# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0020_order_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
