# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0021_auto_20160207_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='client',
            new_name='cc',
        ),
        migrations.AddField(
            model_name='bill',
            name='casher',
            field=models.CharField(default='cacher', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='bill',
            name='tel',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='waiter',
            field=models.CharField(default='waiter', max_length=45),
            preserve_default=False,
        ),
    ]
