# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0022_auto_20160216_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
