# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0023_auto_20160216_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
