# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0024_bill_total_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_tip',
            new_name='totaltip',
        ),
    ]
