# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0025_auto_20160216_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuracion', 'verbose_name_plural': 'Tu configuracion'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'Item de Orden', 'verbose_name_plural': 'Items de Orden'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Presentaci\xf3n', 'verbose_name_plural': 'Presentaciones'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='userservice',
            options={'verbose_name': 'Usuario a Servicio', 'verbose_name_plural': 'Usuarios a Servicio'},
        ),
        migrations.AddField(
            model_name='bill',
            name='ipoconsumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IpoConsumo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='iva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='service',
            name='moviles',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='printer',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='card',
            field=models.CharField(default='0', max_length=45, verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cash',
            field=models.CharField(max_length=45, verbose_name='Efectivo'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='casher',
            field=models.CharField(max_length=45, verbose_name='Cajero'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cc',
            field=models.CharField(default='', max_length=45, verbose_name='Numero de c\xe9dula'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='check',
            field=models.CharField(default='0', max_length=45, verbose_name='Cheque'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='disscount',
            field=models.CharField(default='0', max_length=45, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(default='', max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='products',
            field=models.TextField(verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tel',
            field=models.CharField(default='', max_length=45, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Propina'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='totaltip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total + Propina'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='waiter',
            field=models.CharField(max_length=45, verbose_name='Mesero'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cc',
            field=models.IntegerField(unique=True, verbose_name='Numero de c\xe9dula'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='config',
            name='ipoconsumo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='propina',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='image',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='category_images/', verbose_name='Ruta de la imagen'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='count',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Bill', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='venta.ItemOrder', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Category', verbose_name='Categor\xeda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Presentation', verbose_name='Presentaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(db_index=True, max_length=45, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
