# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0026_auto_20160407_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPoduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name='C\xf3digo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('current_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Compra de Producto',
                'verbose_name_plural': 'Compras Producto',
            },
        ),
        migrations.CreateModel(
            name='BuyPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('count', models.IntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Presentaci\xf3n de Compra',
                'verbose_name_plural': 'Presentaciones de Compra',
            },
        ),
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('count', models.IntegerField()),
                ('bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.BuyPoduct', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.AddField(
            model_name='buypoduct',
            name='buypresentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.BuyPresentation', verbose_name='Producto'),
        ),
    ]
