# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0027_auto_20160407_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buypoduct',
            options={'verbose_name': 'Compra de Producto', 'verbose_name_plural': 'Compras de Productos'},
        ),
    ]
