# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0028_auto_20160408_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cellar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Cellar', verbose_name='Bodega'),
        ),
    ]
