# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0030_remove_product_cellar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypresentation',
            name='cellar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.Cellar', verbose_name='Bodega'),
            preserve_default=False,
        ),
    ]
