# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0032_auto_20160408_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypresentation',
            name='method',
            field=models.BooleanField(choices=[(True, 'PEPS'), (False, 'UEPS')], default=True, verbose_name='M\xe9todo'),
        ),
    ]
