# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0039_buypresentation_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='venta.Product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Pedido de producto',
                'verbose_name_plural': 'Pedidos de productos',
            },
        ),
    ]
