# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0040_productrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='product',
            field=models.ManyToManyField(to='venta.ItemOrder', verbose_name='Productos'),
        ),
    ]
