# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0041_auto_20160412_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequest',
            old_name='product',
            new_name='products',
        ),
    ]
