# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0042_auto_20160412_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 21, 19, 45, 698551, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
