# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0043_productrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Items del pedido',
            },
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='products',
        ),
    ]
