# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0044_auto_20160412_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='productrequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.ProductRequest', verbose_name='Petici\xf3n de producto'),
            preserve_default=False,
        ),
    ]
