# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0046_auto_20160412_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cc',
            field=models.IntegerField(verbose_name='Numero de c\xe9dula'),
        ),
    ]
