# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-06 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0054_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.RemoveField(
            model_name='imagew',
            name='service',
        ),
        migrations.DeleteModel(
            name='Imagew',
        ),
    ]
