# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0058_service_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='default', max_length=45),
            preserve_default=False,
        ),
    ]
