# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0060_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='venta.Service', verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
