# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-09 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('venta', '0062_auto_20161202_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('state', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Service')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.RemoveField(
            model_name='Waiter',
            name='service',
        ),
        migrations.RemoveField(
            model_name='Waiter',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='Order',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter', to=settings.AUTH_USER_MODEL, verbose_name='Mesero'),
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.Brand', verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
