# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0063_auto_20170109_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
