# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0064_auto_20170110_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
